# --- General options --- #

# Name of website
title: Luke Campbell - Entrepreneur

# Short description of site
description: A personal website created by Luke Campbell to showcase work from his career, side projects, and hobbies.
